### PR TITLE
re #3 Adding test to ensure acct user is created.

### PR DESCRIPTION
**Pull request by lowks**
re #3 Adding test to ensure acct user is created.

### CODE REVIEW

**Comment by lowks** [comment]
@CSNajmi no it will not create it. It will use `getent` to query the `/etc/passwd` to see if user `acct` is there. If not there, the playbook will fail.

**Comment by lowks** [comment]
@CSNajmi yeah good point about the groups also. I will add that.

**Comment by kamarudin-csm** [comment]
Based on Oracle installation, it  good to verify the host 1st before installing the oracle. 

1. OS version 
2. Enough RAM
3. The /etc/hosts
4. The hostname /etc/hostname
5. Package needed 
6. Kernel param /etc/sysctl.conf
7. User and Group
8. ENV setting /home/oracle/.bash_profile

Hope this help :)
@lowks @CSNajmi

**Comment by lowks** [comment]
@kamarudin-csm yeah those can be included in the next tickets. Can elaborate on each ? Currently this script only supports informix and postgresql though

**Comment by raj125z** [comment]
Verify backup directory exists 
should be /backup right? not /tmp.

**Comment by lowks** [comment]
@raj125z yeah `/backup` not `/tmp`. I think @hanantha did that because of testing.

**Comment by lowks** [comment]
@raj125z re #8

**Pull request merged**
